### ISSUE TITLE
Error "PropertyFactory.h(5): Error C1083 : Cannot open include file: 'Launch/Resources/Version.h': No such file or directory"

### ISSUE THREAD

**Issue by Genius-pig** [druhasu/UnrealMvvm#10]
When I copied and pasted this plugin into my project, it give me error `10>PropertyFactory.h(5): Error C1083 : Cannot open include file: 'Launch/Resources/Version.h': No such file or directory`

**Comment by Genius-pig** [comment]
According to https://github.com/CesiumGS/cesium-unreal/issues/674 ,Change it into `#include "Runtime/Launch/Resources/Version.h"` solve, don't know why.

**Comment by druhasu** [comment]
Hey! I noticed this too with 5.4 Preview, but did not yet pushed the update. I don't know why it worked before, because `"Runtime/Launch/Resources/Version.h"` is the only correct way of using it.
May be it depends on `BuildSettingsVersion` your project are using, because mine are still on V2

**Comment by druhasu** [comment]
Fixed in last commit
