### ISSUE TITLE
UUserWidget::NativeConstruct crash in packaged build

### ISSUE THREAD

**Issue by AntiqueAntonio** [druhasu/UnrealMvvm#3]
>	**.exe!UUserWidget::NativeConstruct() Line 1379	C++
 	**.exe!UBaseView::NativeConstruct() Line 27	C++
 	**.exe!UWBaseHeader::NativeConstruct() Line 12	C++
 	**.exe!UWidget::TakeWidget_Private(TFunctionRef<TSharedPtr<SObjectWidget,1> __cdecl(UUserWidget *,TSharedRef<SWidget,1>)> ConstructMethod) Line 999	C++
 	**.exe!UWidget::TakeWidget() Line 916	C++

При загрузке дочерних виджетов в блюпринте виджета значение массива экстеншенов затирается нулем и уже в UserWidget у нас приходит некорректное значение экстеншенов

Проблема появилась после обновления плагина с версии 3.6.0 до последней версии

**Comment by druhasu** [comment]
Исправлено в версии 4.1.2.

Для исправления нужно будет пересохранить все виджеты, внутри которых есть дочерние View виджеты, и после этого перезапустить редактор.

**Comment by nverenik** [comment]
@druhasu А нет возможности сразу добавить какое-то версионирование (с какой версией плагина был сохранен ассет)? Не понятно правда, где эту версию хранить, тегом к ассету например? Условно, чтобы при загрузке UMG ассета в память можно было отследить, что версия обновилась и автоматом тригерить компиляцию/сохранение?

**Comment by druhasu** [comment]
@nverenik Да, можно сохранить версию в ассете. Но в этом конкретном случае косячил сам движок. Свойство UUserWidget::Extensions не помечно как Transient. Из-за этого, если туда добавить что-то не в рантайме, оно сохранится в ассет. А вот загрузиться нормально не сможет, оставив вместо себя nullptr
