### ISSUE TITLE
GetViewModelPropertyValue accesibility compilation error on Mac

### ISSUE THREAD

**Issue by AntiqueAntonio** [druhasu/UnrealMvvm#4]
При компиляции модуля редактора на маке получаем следующее:

> 08:00:10   [335/647] Compile Module.UnrealMvvmEditor.cpp
08:00:10   In file included from /**/Plugins/UnrealMvvm/UnrealMvvm/Intermediate/Build/Mac/x86_64/UnrealEditor/Development/UnrealMvvmEditor/Module.UnrealMvvmEditor.cpp:17:
08:00:10   /**/Plugins/UnrealMvvm/UnrealMvvm/Source/UnrealMvvmEditor/Private/ViewModelPropertyNodeHelper.cpp:151:123: error: 'GetViewModelPropertyValue' is a private member of 'UMvvmBlueprintLibrary'
08:00:10           GetViewModelPropertyValueCall->FunctionReference.SetExternalMember(GET_MEMBER_NAME_CHECKED(UMvvmBlueprintLibrary, GetViewModelPropertyValue), UMvvmBlueprintLibrary::StaticClass());
08:00:10                                                                                                                             ^
08:00:10   /**/Plugins/UnrealMvvm/UnrealMvvm/Source/UnrealMvvm/Public/Mvvm/MvvmBlueprintLibrary.h:28:17: note: declared private here
08:00:10       static void GetViewModelPropertyValue(UUserWidget* View, FName PropertyName, int32& Value, bool& HasValue);
08:00:10                   ^
08:00:10   1 error generated.

На винде все ок

**Comment by druhasu** [comment]
Исправлено в версии 4.1.3
