### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by michaelWuensch** [druhasu/UnrealMvvm#6]
There is no information in the readme at all.
Is this the repo for the official MVVM plugin that ships with unreal or is this a completely different implementation?

**Comment by druhasu** [comment]
Hello and thanks for the feedback! I'll put readme on top of my to-do list.
This is a different implementation. I started it long before Epic games announced their plugin.

**Comment by druhasu** [comment]
Updated readme with basic information about plugin
