### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by BackupPlease** [druhasu/UnrealMvvm#8]
Hello

 I am trying to build after making the Model but I am getting this error 

UE 5.3

![rider64_0yvWRfRif0](https://github.com/druhasu/UnrealMvvm/assets/129668534/0e5a2ba6-c7a6-4f32-9057-54c6b9f38a23)

**Comment by druhasu** [comment]
Hello!
I did not update the plugin for 5.3 yet. Will look into it today

**Comment by BackupPlease** [comment]
Cheers mate :) can't wait to use it for my game

**Comment by druhasu** [comment]
Fixed in [4.4.2](https://github.com/druhasu/UnrealMvvm/releases/tag/v4.4.2)
